### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by nossilcd** [QVDev/GunPushToTalk#1]
Apparently the audio isn't being transmitted anymore as of 1-10-2020.

**Comment by QVDev** [comment]
@nossilcd yeah it seems some issue with heroku/gun. What you can try is the following:

- In index.js on line 1 there are two peers defined.
- copy one peer at the time and visit in the browser
- Add some items to make Gun a live in heroku
- Do this for both peers.

Then try afterwards the gun push to talk it should work now. I havent got time yet to find the issue so feel free👍 thanks for the issue

**Comment by QVDev** [comment]
Have fixed this seems passing opt with localstorage and radisk false is giving me issues. Upgraded also the heroku gun instance. Everything should work again @nossilcd
